### ISSUE TITLE
test.wav file of about 6gb is being created on local machine

### ISSUE THREAD

**Issue by nimblefox** [TheSoundOfAIOSR/rg_production#22]
Have been seeing a test.wav file being created in my local repository and it slowly grows in size to ~6gb.
Need to find the cause and stop generating it
![image](https://user-images.githubusercontent.com/20728362/115929823-09bf7200-a4a6-11eb-99bc-dd55163dbc1a.png)

**Comment by Leofltt** [comment]
fixed already
